services:
  debros-node-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '7777:7777'
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./orbitdb:/app/orbitdb
      - ./blockstore:/app/blockstore
      - ./keys:/app/keys
      - ./.env:/app/.env
      - ./terms-agreement:/app/terms-agreement
      - ./logs:/app/logs
    environment:
      - PORT=7777
      - NODE_ENV=development
      # Add other environment variables if needed
    networks:
      - debros-network

networks:
  debros-network:
    driver: bridge
